"""Contraints for many to many relationships

Revision ID: 0d49b55660d0
Revises: 5abd73560ac5
Create Date: 2025-04-01 18:40:39.568796

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0d49b55660d0'
down_revision = '5abd73560ac5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('deck_tag', schema=None) as batch_op:
        batch_op.alter_column('deck_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('tag_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('deck_tag', schema=None) as batch_op:
        batch_op.alter_column('tag_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('deck_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###
