"""Unique tag name

Revision ID: 5abd73560ac5
Revises: e46ba2ad1b03
Create Date: 2025-03-30 11:52:40.249209

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5abd73560ac5'
down_revision = 'e46ba2ad1b03'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tags', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_tags_name'), ['name'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tags', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_tags_name'), type_='unique')

    # ### end Alembic commands ###
