"""Tags

Revision ID: e46ba2ad1b03
Revises: 66e4dff3b131
Create Date: 2025-03-19 11:50:19.978102

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e46ba2ad1b03'
down_revision = '66e4dff3b131'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tags',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=32), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tags'))
    )
    op.create_table('deck_tag',
    sa.Column('deck_id', sa.Integer(), nullable=True),
    sa.Column('tag_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['deck_id'], ['decks.id'], name=op.f('fk_deck_tag_deck_id_decks')),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], name=op.f('fk_deck_tag_tag_id_tags'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('deck_tag')
    op.drop_table('tags')
    # ### end Alembic commands ###
